_format_version: "3.0"
_transform: true

services:
  - host: host.docker.internal
    port: 8800
    name: caliwears_product_server
    path: /api/products
    routes:
      - name: product-service
        paths:
          - /products
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

- name: rate-limiting
  config:
    # second: 5
    hour: 10
    policy: local
