plugins:
  - name: cors
    config:
      origins:
        - http://127.0.0.1:8800
      methods:
        - GET
        - POST
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

- name: rate-limiting
  config:
    second: 5
    hour: 100
    policy: local