_format_version: "3.0"

services:
  - name: products
    url: http://127.0.0.1:8000/api/products
    routes:
      - name: product
        paths:
          - /api/products

upstreams:
  - name: product_service
    targets:
      - target: 127.0.0.1:8800
# plugins:
#   - name: cors
#     config:
#       origins:
#         - "*"
#       methods:
#         - GET
#         - POST
#       headers:
#         - Accept
#         - Accept-Version
#         - Content-Length
#         - Content-MD5
#         - Content-Type
#         - Date
#         - X-Auth-Token
#       exposed_headers:
#         - X-Auth-Token
#       credentials: true
#       max_age: 3600

# - name: rate-limiting
#   config:
#     # second: 5
#     hour: 10
#     policy: local
