_format_version: "3.0"
_transform: true

services:
  - name: cali_product_service
    host: host.docker.internal
    port: 8080
    path: /api/products
    routes:
      - name: product_resource_endpoint
        methods:
          - GET
        paths:
          - /products
        strip_path: true
  - name: cali_inventory_service
    host: host.docker.internal
    port: 8800
    path: /api/inventories
    routes:
      - name: inventory_resource_endpoint
        methods:
          - GET
          - POST
        paths:
          - /inventory
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  - name: rate-limiting
    config:
      second: 5
      hour: 10
      policy: local
